# Configuration options can be accessed as
# configatron.site_name

development: &local
    site_name: eLearning
    site_namemobile: eLearingM
    site_url: baseapp2.local
    
    company_name: Development Company
    admin_email: admin@baseapp2.local
    
    support_name: BaseApp2 Support
    support_email: support@baseapp2.local
    
    site_envnote: Local Server

    site_envnote: 192.168.0.90:8080

    school_name: 七中育才学校
    school_desc: 七中育才学校
production:
    site_name: BaseApp2
    site_namemobile: BaseApp2
    site_url: www.baseapp2.com
    
    company_name: Development Company
    admin_email: admin@baseapp2.com
    
    support_name: Development Company
    support_email: support@baseapp2.com
    
    site_envnote: 192.168.0.90:8080

    school_name: 七中育才学校
    school_desc: 七中育才学校  
staging:
  <<: *local

test:
  <<: *local
